CREATE TABLE [dbo].[Person] (
	[ID] INT IDENTITY(1, 1) PRIMARY KEY
	,[Titlu] NVARCHAR(MAX) NULL
	,[Nume] NVARCHAR(MAX) NULL
	,[Prenume] NVARCHAR(MAX) NULL
	,[DataNasterii] DATETIME NULL
	,[Ocupatie] NVARCHAR(MAX) NULL
	,[Sex] NVARCHAR(1) NULL 
	)
